# fly.toml app configuration file generated for cjs-team-1-app on 2023-06-26T14:32:37+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cjs-team-1-app"
primary_region = "sin"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  DB_CONNECTION="pgsql"
  DB_HOST="db.owlavinmrnbnpzqtopgy.supabase.co"
  DB_PORT="5432"
  DB_DATABASE="postgres"
  DB_USERNAME="postgres"
  DB_PASSWORD="cjs-team-1-app"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
